### ISSUE TITLE
Failed to start OpenBSD Secure Shell server

### ISSUE THREAD

**Issue by fpgags** [RedPitaya/RedPitaya#285]
Hi,
This is my first time using the board and updating the firmware version to RedPitaya-OS_2.00-30_stable. An error occurred during startup and kept restarting. How can I solve this problem?
![1](https://github.com/RedPitaya/RedPitaya/assets/58766526/2ef721f3-db82-401d-a6ff-5bcafccb3e3c)
I tried updating the firmware to an older version but it still couldn't function properly. Before version 0.99, it can start normally but cannot be accessed on the web.PC can ping successfully, but web access will crash directly.

**Comment by fpgags** [comment]
STEMlab_125-xx_OS_0.99-41_beta
Unable to access web. The system will crash and display Getting the list of applications.
![2](https://github.com/RedPitaya/RedPitaya/assets/58766526/04a7ba8a-497e-4e1b-92eb-78ad29e2c747)
![3](https://github.com/RedPitaya/RedPitaya/assets/58766526/23947836-dc2f-4e39-84d9-784483e5d86a)
![4](https://github.com/RedPitaya/RedPitaya/assets/58766526/121d9a95-2acb-4fa8-bf5e-50e69637346d)
![5](https://github.com/RedPitaya/RedPitaya/assets/58766526/d2770fdf-030a-412d-9dea-c3ac532e2e8a)

**Comment by b-swat** [comment]
Hi
The problem with OpenBSD Secure Shell server is known to me.
I don't know how to fix it yet. The server does not start because the SSH service takes a long time to create certificates.
This happens on the first startup after writing to the SD card.
This does not cause any discomfort. ssh is available some time after the certificates are created.

And the problem with rebooting is not related to the OpenBSD server.
This bug is known to me; it was also fixed in build 35.
Problem with incorrect uboot initialization.
On some boards 30 build may not work.

**Comment by fpgags** [comment]
Thank you for your answer
